apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong-dependencies
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/usrbinkat/kong-gitops.git
    targetRevision: HEAD
    path: kong/kustomize
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cert-manager
