apiVersion: v1
data:
  admin_gui_session_conf: eyJzdG9yYWdlIjoia29uZyIsInNlY3JldCI6InN1cGVyX3NlY3JldF9zYWx0X3N0cmluZyIsImNvb2tpZV9uYW1lIjoiYWRtaW5fc2Vzc2lvbiIsImNvb2tpZV9zYW1lc2l0ZSI6Im9mZiIsImNvb2tpZV9zZWN1cmUiOmZhbHNlfQ==
  kong_admin_password: a29uZw==
  password: a29uZw==
  pg_host: ZW50ZXJwcmlzZS1wb3N0Z3Jlc3FsLmtvbmcuc3ZjLmNsdXN0ZXIubG9jYWw=
  portal_session_conf: eyJzdG9yYWdlIjoia29uZyIsInNlY3JldCI6InN1cGVyX3NlY3JldF9zYWx0X3N0cmluZyIsImNvb2tpZV9uYW1lIjoicG9ydGFsX3Nlc3Npb24iLCJjb29raWVfc2FtZXNpdGUiOiJvZmYiLCJjb29raWVfc2VjdXJlIjpmYWxzZX0=
kind: Secret
metadata:
  creationTimestamp: null
  name: kong-config-secret
  namespace: kong
