apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong-gateway
  namespace: argocd
spec:
  project: default
  source:
    chart: kong
    repoURL: https://usrbinkat.github.io/charts/
    targetRevision: 2.14.0
    helm:
      releaseName: kong-gateway
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kong
